#!/bin/sh

set -eu

install_lua_pkg() {
    if ! check_command lua; then
        error "Lua is not installed or not in '\$PATH'." && return 1
    elif [ $# -eq 0 ]; then
        error "No package given. Please provide at least one packge." && return 1
    fi

    if ! luarocks install --local "$@"; then
        error "Failed to installes packages." && return 1
    fi

    success "Finished package installation." && return 0
}
