#!/bin/sh


if [ -z "${SCRIPT_DIR:-}" ]; then
    SCRIPT_DIR=$(dirname "$(dirname "$PWD")")
fi

. "${SCRIPT_DIR}/utils" || exit 1

identify_system_pkg_mgr() {
    if [ -z "${PKG_MGR}" ]; then
        info "Identifing package manger."
        if check_command apt-get; then
            export PKG_MGR="apt-get"
        elif check_command dnf; then
            export PKG_MGR="dnf"
        else
            warning "No valid package manager found." && return 1
        fi
    else
        debug "Package manager was already defined as '${PKG_MGR}'"
    fi
    success "Identified '${PKG_MGR}' as package manager." && return 0
}

install_packages_with_pkg_mgr() {
    if [ -z "${PKG_MGR:-}" ]; then
        error "Need to set 'PKG_MGR', or call 'identify_system_pkg_mgr'." && return 2
    fi

    if [ $# -eq 0 ]; then
        error "No package given. Please provide at least one packge." && return 3
    fi

    info "Installing: $* ..."
    debug "Updating repositories."

    if ! sudo "${PKG_MGR}" update -y; then
        warning "Can not update the package repositories."
    fi

    debug "Installing package(s)."
    if ! sudo "${PKG_MGR}" install -y "$@"; then
        error "Can not install package(s)." && return 1
    fi

    success "Installed packages: $*" && return 0
}
