#!/bin/sh

set -eu

if [ -z "${SCRIPT_DIR:-}" ]; then
    SCRIPT_DIR=$(dirname "$(dirname "$PWD")")
fi

. "${SCRIPT_DIR}/utils" || exit 1

install_rust() {
    if check_command rustc; then
        info "Rust is already installed." && return 0
    fi
    CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
    debug "CARGO_HOME is set to '${CARGO_HOME}'."
    info "Downloading and installing rust..."

    debug "Download rust ..."
    if ! output=$(curl -o /tmp/rust.sh --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs 2>&1); then
        error "Curl failed. Output: ${output}"
        return 1
    fi

    debug "Installing rust ... "
    if ! output=$(sh /tmp/rust.sh -y 2>&1); then
        error "Rust installation failed. Output: ${output}"
        debug "Deleting rust install script."
        return 1
    fi

    echo ":$PATH:" | grep -q ":${CARGO_HOME}/bin:" || export PATH="${CARGO_HOME}/bin:${PATH}"

    debug "Added '${CARGO_HOME}/bin' to PATH"
    success "Rust has been successfully installed."
    return 0
}

install_rust
