#!/bin/sh

[ -z "$SCRIPT_DIR" ] && SCRIPT_DIR="$(pwd)/../scripts"

. "${SCRIPT_DIR}/log"

install_rust() {
    if command -v rustc >/dev/null 2>&1; then
        info "Rust is already installed."
        return 0
    fi
    debug "Prepare to install Rust."

    if [ -z "${CARGO_HOME}" ]; then
        CARGO_HOME="${HOME}/.cargo"
    fi
    CARGO_BIN="${CARGO_HOME}/bin"
    debug "Set cargo bin path to '${CARGO_BIN}'"

    info "Downloading and installing rust."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y || return 1
    echo ":$PATH:" | grep -q ":$CARGO_HOME/bin:" || export PATH="${CARGO_BIN}:${PATH}"

    success "Installed rust"
    return 0
}

install_selene() {
    info "Installing selene ..."
    if ! install_rust; then
        warning "Could not install rust."
        error "Cancel installation of selene."
        return 1
    fi
    cargo install selene || return 1
    success "Installed selene."
    return 0
}
