#!/usr/bin/env bash

set -e

NVIM_DEV=false
INSTALL_NERD_FONTS=false

SCRIPT_DIR="$(pwd)/installs"
DEPENDENCIES=$(pwd)/dependencies

source "${SCRIPT_DIR}/utils" || {
    info "No production install found."
    exit 2
}

if ! source "${DEPENDENCIES}"; then
    error "No dependencies found."
    debug "Expect dependency file at ${DEPENDENCIES}"
    exit 1
fi

source "${SCRIPT_DIR}/prod" || {
    info "No production install found."
    exit 3
}

for arg in "$@"; do
    case "$arg" in
        dev)
            NVIM_DEV=true
            ;;
        --nerd-fonts)
            INSTALL_NERD_FONTS=true
            source "${SCRIPT_DIR}/nerd-fonts" || {
                info "Nerd-fonts install not found."
                exit 4
            }
            ;;
    esac
done

main() {
    if ${INSTALL_NERD_FONTS}; then
        init_nerd_process
        info "Cloning nerd-fonts in background."
    else
        info "Skipping nerd-fonts installation."
        info "Please install nerd-fonts 'https://github.com/ryanoasis/nerd-fonts'."
    fi

    if ! install_prod; then
        error "Can not install production."
        if ${INSTALL_NERD_FONTS}; then
            kill_nerd_fonts_process
        fi
        return 5
    fi

    if ${NVIM_DEV}; then
        source "${SCRIPT_DIR}/dev" || {
            info "No dev install found."
            exit 6
        }
        if ! install_dev; then
            error "Can not install development dependencies."
            if ${INSTALL_NERD_FONTS}; then
                kill_nerd_fonts_process
            fi
            return 7
        fi
    fi

    info "Installing language-servers, formaters and linters ... "
    PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH" nvim --headless "+InitNVIM"
    echo "\n"

    if ${INSTALL_NERD_FONTS}; then
        install_nerd_fonts
    fi

    info "You need to set a '${CARGO_HOME}/bin' in your path permanently to enable mason future updates."
    success "Setup nvim successfully. Enjoy it :)"
    return 0
}

main "$@"
