#!/usr/bin/env bash

set -e

NVIM_DEV=false
INSTALL_NERD_FONTS=false

for arg in "$@"; do
    case "$arg" in
        dev)
            NVIM_DEV=true
            ;;
        --nerd-fonts)
            INSTALL_NERD_FONTS=true
            ;;
    esac
done

DEPENDENCIES=$(pwd)/dependencies
SCRIPT_DIR="$(pwd)/installs"

source "${SCRIPT_DIR}/utils" || {
    info "No production install found."
    exit 1
}

if ! source "${DEPENDENCIES}"; then
    error "No dependencies found."
    debug "Expect dependency file at ${DEPENDENCIES}"
    exit 1
fi

source "${SCRIPT_DIR}/prod" || {
    info "No production install found."
    exit 1
}

main() {
    if $INSTALL_NERD_FONTS; then
        init_clone_process
        info "Cloning nerd-fonts in background."
    else
        info "Skipping nerd-fonts installation."
        info "Please install nerd-fonts 'https://github.com/ryanoasis/nerd-fonts'."
    fi

    if ! install_system_dependencies; then
        error "Stopping installation. Can't install system dependencies."
        exit 1
    fi
    if ! check_nvim_version; then
        error "Neovim version v0.11.4 or higher is required.\n
        Please install it before you can continue with the installation."
        exit 1
    fi

    if ! install_selene; then
        warning "Can not install selene. Continue ..."
    fi

    if ! install_lpeglabel; then
        warning "Can not install lpeglabel. Continue ..."
    fi

    info "Installing language-servers, formaters and linters ... "
    PATH="${CARGO_HOME:-$HOME/.cargo}/bin:$PATH" nvim --headless "+InitNVIM"
    echo "\n"

    if [ "$1" = "--nerd-fonts" ]; then
        install_nerd_fonts
    fi

    info "You need to set a '${CARGO_HOME}/bin' in your path permanently to enable mason future updates."
    success "Setup nvim successfully. Enjoy it :)"
    return 0
}

main "$@"
