#!/bin/sh


if [ -z "${SCRIPT_DIR:-}" ]; then
    SCRIPT_DIR=$(dirname "$(dirname "$PWD")")
fi

. "${SCRIPT_DIR}/utils/logger" || exit 1

is_repo() {
    if [ "$#" -ne 1 ]; then
        error "Function needs exactly one 'path' argument." && return 1
    fi

    path=$1
    if [ ! -d "${path}" ]; then
        error "Path '${path}' does not exist or is not a directory." && return 1
    fi

    if ! git -C "${path}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        error "Path '${path}' is not a git repo." && return 1
    fi

    success "Path '${path}' is a git repo."
    return 0
}

pull_repo() {
    if [ "$#" -ne 1 ]; then
        error "Function needs exactly one 'path' argument." && return 1
    fi

    path=$1
    if [ ! -d "${path}" ]; then
        error "Path '${path}' does not exist or is not a directory." && return 1
    fi

    git -C "${path}" checkout main 2>/dev/null \
        || git -C "${path}" checkout master 2>/dev/null \
        || true

    if ! git -C "${path}" pull; then
        error "Can not pull repo at '${path}'." && return 1
    fi

    success "Pulled repo at '${path}'." && return 0
}

clone_repo() {
    if [ "$#" -ne 2 ]; then
        error "Function needs exactly two arguments, 'repo-url' and 'dest-dir'." && return 2
    fi

    repo_url=$1
    dest_dir=$2
    tmpfile=$(mktemp)

    git clone --depth=1 "${repo_url}" "${dest_dir}" >"${tmpfile}" 2>&1 &
    echo "$! ${tmpfile}"
    return 0
}

wait_for_clone_process() {
    if [ "$#" -ne 2 ]; then
        error "Function needs exactly two arguments, 'pid' and 'tmpfile'." && return 2
    fi

    pid=$1
    tmpfile=$2

    info "Waiting for clone process ${pid} to finish."
    if ! tail --pid="${pid}" -f "${tmpfile}"; then
        error "Can not tail ${tmpfile}." && return 3
    fi

    if ! wait "${pid}"; then
        error "Can not wait ${pid}." && return 1
    fi

    rm -f "${tmpfile}"
    success "Clone process ${pid} finished." && return 0
}

kill_clone_process() {
    if [ "$#" -ne 1 ]; then
        error "Function needs exactly one 'pid' argument." && return 2
    fi

    pid=$1
    if ! kill "${pid}"; then
        error "Can not kill nerd-fonts process '${pid}'." && return 1
    fi

    success "Killed process ${pid}." && return 0
}
