#!/bin/sh

set -e

[ -z "$SCRIPT_DIR" ] && SCRIPT_DIR="$(pwd)/../../scripts"

. "${SCRIPT_DIR}/log"

install_packages_with_pkg_mgr() {
    if [ -z "${PKG_MGR}" ]; then
        warning "Need to set 'PKG_MGR', or call 'identify_system_pkg_mgr'."
        return 3
    elif [ $# -eq 0 ]; then
        warning "No package given. Please provide at least one packge."
        return 2
    fi

    PACKAGES="$*"
    info "Installing: ${PACKAGES} ..."
    debug "Updating repositories."
    if ! sudo "${SYSTEM_PKG_MGR}" update -y; then
        warning "Can not update the package repositories."
    fi

    debug "Installing package(s)."
    if ! sudo "${SYSTEM_PKG_MGR}" install -y "$@"; then
        error "Can not install package(s)."
        return 1
    fi

    success "Installed packages: ${PACKAGES}"
    return 0
}

identify_system_pkg_mgr() {
    if [ -z "${PKG_MGR}" ]; then
        info "Identifing package manger."
        if command -v apt-get >/dev/null 2>&1; then
            PKG_MGR="apt-get"
        elif command -v dnf >/dev/null 2>&1; then
            PKG_MGR="dnf"
        else
            warning "No valid package manager found."
            return 1
        fi
    else
        debug "Package manager was already defined as '${PKG_MGR}'"
    fi
    success "Identified '${PKG_MGR}' as package manager."
    return 0
}

install_rust() {
    if command -v rustc >/dev/null 2>&1; then
        info "Rust is already installed."
        return 0
    fi

    CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
    debug "CARGO_HOME is set to '${CARGO_HOME}'."

    info "Downloading and install rust..."
    if ! curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; then
        error "Installation of rust failed."
        return 1
    fi
    echo ":$PATH:" | grep -q ":${CARGO_HOME}/bin:" || export PATH="${CARGO_HOME}/bin:${PATH}"

    success "Installed rust."
    return 0
}
