#!/bin/sh

install_rust_pkg() {
    if ! command -v rustc >/dev/null 2>&1 || ! command -v cargo >/dev/null 2>&1; then
        warning "Rust is not installed or rust and cargo not in '\$PATH'."
        return 3
    elif [ ! -n "$1" ]; then
        warning "No package given. Please provide at least one packge."
        return 2
    fi
    PACKAGES="$*"
    info "Installing rust package(s): ${PACKAGES} ..."
    if ! cargo ${PACKAGES}; then
        error "Can not install rust package(s)"
        return 1
    fi

    success "Installed rust package(s): ${PACKAGES}"
    return 0
}
