#!/bin/sh

install_rust() {
    if command -v rustc >/dev/null 2>&1; then
        info "Rust is already installed."
        return 0
    fi

    CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
    debug "CARGO_HOME is set to '${CARGO_HOME}'."

    info "Downloading and install rust..."
    if ! curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y; then
        error "Installation of rust failed."
        return 1
    fi
    echo ":$PATH:" | grep -q ":${CARGO_HOME}/bin:" || export PATH="${CARGO_HOME}/bin:${PATH}"

    success "Installed rust."
    return 0
}

install_rust_pkg() {
    if ! command -v rustc >/dev/null 2>&1 || ! command -v cargo >/dev/null 2>&1; then
        warning "Rust is not installed or rust and cargo not in '\$PATH'."
        return 3
    elif [ ! -n "$1" ]; then
        warning "No package given. Please provide at least one packge."
        return 2
    fi
    PACKAGES="$*"
    info "Installing rust package(s): ${PACKAGES} ..."
    if ! cargo ${PACKAGES}; then
        error "Can not install rust package(s)"
        return 1
    fi

    success "Installed rust package(s): ${PACKAGES}"
    return 0
}
