#!/bin/sh

[ -z "$SCRIPT_DIR" ] && SCRIPT_DIR="$(pwd)/../../scripts"

. "${SCRIPT_DIR}/log"

install_pck() {
    [ ! -z "$PKG_MGR" ] && warning "Need to set 'PKG_MGR', or call 'identify_system_pkg_mgr'." && exit 1
    PACKAGES="$*"
    info "Installing: {$PACKAGES} ..."
    debug "Updating repositories."
    sudo "${SYSTEM_PKG_MGR}" update -y || return 1

    debug "Installing dependencies."
    sudo "${SYSTEM_PKG_MGR}" install -y "$@" || return 1

    success "Installed packages: {$PACKAGES}"
    return 0
}

identify_system_pkg_mgr() {
    if [ -z "$PKG_MGR" ]; then
        info "Identifing package manger."
        if command -v apt-get >/dev/null 2>&1; then
            PKG_MGR="apt-get"
        elif command -v dnf >/dev/null 2>&1; then
            PKG_MGR="dnf"
        else
            warning "No valid package manager found."
            return 1
        fi
    else
        debug "Package manager was already defined as '${PKG_MGR}'"
    fi
    success "Identified '${PKG_MGR}' as package manager."
    return 0
}
