#!/bin/sh

[ -z "$SCRIPT_DIR" ] && SCRIPT_DIR="$(pwd)/../../scripts"

. "${SCRIPT_DIR}/log"

install_pck() {
    if [ ! -z "${PKG_MGR}" ]; then
        warning "Need to set 'PKG_MGR', or call 'identify_system_pkg_mgr'."
        return 1
    elif [ ! -n "$1" ]; then
        warning "No package given. Please provide at least one packge."
        return 1
    fi

    PACKAGES="$*"
    info "Installing: ${PACKAGES} ..."
    debug "Updating repositories."
    if ! sudo "${SYSTEM_PKG_MGR}" update -y; then
        warning "Can not update the package repositories."
    fi

    debug "Installing package(s)."
    if ! sudo "${SYSTEM_PKG_MGR}" install -y "$@"; then
        error "Can not install package(s)."
        return 1
    fi

    success "Installed packages: ${PACKAGES}"
    return 0
}

identify_system_pkg_mgr() {
    if [ -z "${PKG_MGR}" ]; then
        info "Identifing package manger."
        if command -v apt-get >/dev/null 2>&1; then
            PKG_MGR="apt-get"
        elif command -v dnf >/dev/null 2>&1; then
            PKG_MGR="dnf"
        else
            warning "No valid package manager found."
            return 1
        fi
    else
        debug "Package manager was already defined as '${PKG_MGR}'"
    fi
    success "Identified '${PKG_MGR}' as package manager."
    return 0
}
