FROM fedora:42
ENV DISPLAY=:99
ENV TERM=xterm

SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

USER root

RUN python -m pip install --no-cache-dir pre-commit==4.2.0

USER tester

WORKDIR "${NVIM_CONFIG}"
