return {
	cmp = {
		Class = "",
		Color = "",
		Constant = "",
		Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Function = "󰊕",
		Interface = "",
		Keyword = "",
		Method = "󰡱",
		Module = "",
		Operator = "",
		Property = "",
		Reference = "",
		Snippet = "",
		Struct = "",
		Text = "󰦨",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "󰫧",
	},
	diagnostics = {
		error = "",
		hint = "",
		icon = "",
		info = "",
		warning = "",
	},
	development = {
		_function = "󰊕",
		class = "",
		file = "",
		git = "",
		type_parameter = "",
	},
	git = {
		add = "+",
		branch = "",
		change = "│",
		changes = {
			added = "+",
			deleted = "-",
		},
		changedelete = "~",
		delete = "-",
		icon = "",
		ignored = "◌",
		pull = "",
		push = "",
		pushpull = "",
		renamed = "➜",
		staged = "✓",
		topdelete = "-",
		unmerged = "",
		unstaged = "✗",
		untracked = "┆",
	},
	lsp = {
		action = "",
		def = "",
		icon = "",
		reference = "",
		show_def = "",
		_goto = "",
		usage = "",
	},
	mason = {
		package_installed = "✓",
		package_pending = "➜",
		package_uninstalled = "✗",
	},
	quit = {
		exit = "󰩈",
		icon = "󰖭",
	},
	refactor = {
		block_to_file = "",
		color = "",
		conceal = "󱅉",
		extract_block = "",
		format = "󰣪",
		icon = "",
		inline_method = "󰡱",
		inline_variable = "󱍔",
		selection_to_file = "󰟦",
		selection_to_method = "",
		selection_to_variable = "󰑕",
		selection_variable = "󱌣",
	},
	system = {
		directory = {
			browse = "󱞊",
			config = "",
			default = "",
			empty = {
				default = "",
				open = "",
			},
			git = "",
			home = "󱂵",
			nvim = "",
			open = "",
			project = "",
			root = "",
			search = "󰥨",
		},
		file = {
			browse = "󰷋",
			default = "",
			md = "󰍔",
			new = "",
			search = "󰱽",
		},
		links = {
			directory = "",
			file = "",
			project = "",
		},
		utils = {
			shell = "",
		},
	},
	telescope = {
		prompt = "",
		selection = "",
	},
	ui = {
		input = {
			title = "",
		},
		modified = {
			isModified = "",
			isNotModified = "",
			isReadonly = "󱙃",
		},
		padding = " ",
		separator = {
			default = "|",
			left = {
				line = "▎",
				soft_divider = "",
				triangle = "",
				upper = "",
			},
			right = {
				close = "|",
				line = "▕",
				soft_divider = "",
				triangle = "",
				upper = "",
			},
		},
		statusline = {
			battery = {
				["not charging"] = "󰂃",
				charging = {
					[0] = "󰢟",
					[10] = "󰢜",
					[20] = "󰂆",
					[30] = "󰂇",
					[40] = "󰂈",
					[50] = "󰢝",
					[60] = "󰂉",
					[70] = "󰢞",
					[80] = "󰂊",
					[90] = "󰂋",
					[100] = "󰂅",
				},
				discharging = {
					[0] = "󰂎",
					[10] = "󰢜",
					[20] = "󰁻",
					[30] = "󰁼",
					[40] = "󰁽",
					[50] = "󰁾",
					[60] = "󰁿",
					[70] = "󰂀",
					[80] = "󰂁",
					[90] = "󰂂",
					[100] = "󰁹",
				},
				full = "󰁹",
				unknown = "󰂑",
			},
			datetime = {
				date = "",
				time = "",
			},
			os = {
				linux = "",
				mac = "",
				unkown = "",
				windows = "",
			},
		},
		tabline = {
			boundaries = {
				more = {
					left = "",
					right = "",
				},
			},
			close = { sign = "󰖭", separator = "|" },
			separator = {
				close = "|",
				left = "▕",
				right = "▎",
			},
		},
		winbar = {
			active = "",
		},
	},
	whichkey = {
		break_line = "󰘌",
		close = "",
		copilot = "",
		deleted = "",
		focus = "",
		help = "󰋖",
		list = "",
		login = "󰍂",
		logout = "󰍃",
		next = "󰁔",
		open = "",
		previous = "󰁍",
		refresh = "",
		ssh = {
			icon = "󰣀",
			info = "",
			clean = "󰉥",
			clean_up = "",
			logs = "",
		},
		status = "",
		toggle = "󰨚",
		tree = "󰔱",
		undo = "",
		telescope = {
			browse = "󰥨",
			browse_old = "",
			docker = "󰡨",
			find_file = "󰱼",
			icon = "󰭎",
			nvim = "",
			projects = "",
			search = "󱘞",
			grep = "",
		},
	},
}
