FROM fedora:42

ENV DISPLAY=:99
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Create TestUser
RUN mkdir -p /home/tester && groupadd tester
ENV HOME=/home/tester

RUN useradd -m -g tester tester
ENV NVIM_HOME="${HOME}/.config/nvim"

# clone and install nvim from github.
RUN dnf update && dnf install -y ninja-build cmake gcc make gettext curl glibc-gconv-extra git && dnf clean all
ENV MAJOR_REQ=0
ENV MINOR_REQ=11
ENV PATCH_REQ=4

RUN mkdir -p "${HOME}/.local/share/src"
ENV NVIM_GIT_DIR="${HOME}/.local/share/src/neovim"

RUN git clone https://github.com/neovim/neovim -b "v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}" "${NVIM_GIT_DIR}" || exit 1
WORKDIR "${NVIM_GIT_DIR}"
RUN make CMAKE_BUILD_TYPE=Release && make install

WORKDIR "${NVIM_HOME}"

COPY ./ .

ENTRYPOINT ["/home/tester/.config/nvim/tests/entrypoint"]
