#!/usr/bin/env bash

set -e

get_log_color() {
    local level="$1"
    case "$level" in
        DEBUG) printf "\033[37m" ;;
        INFO) printf "\033[34m" ;;
        SUCCESS) printf "\033[32m" ;;
        WARNING) printf "\033[33m" ;;
        ERROR) printf "\033[31m" ;;
        *) printf "\033[0m" ;;
    esac
}

log() {
    local level="$1"
    shift
    local color
    color="$(get_log_color "${level}")"
    printf "%b[%s]%b %-7s| %b%s%b\n" "\033[36m" "$(date +'%H:%M:%S')" "${color}" "${level}" "\033[37m" "$*" "\033[0m"
}

debug() {
    if ${NVIM_DEV}; then
        log "DEBUG" "$*"
    fi
}
info() {
    log "INFO" "$*"
}
success() {
    log "SUCCESS" "$*"
}
warning() {
    log "WARNING" "$*"
}
error() {
    log "ERROR" "$*"
}
