#!/usr/bin/env bash

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
DEPENDENCIES="${DEPENDENCIES:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../dependencies}"

source "${SCRIPT_DIR}/utils" || exit 1
source "${DEPENDENCIES}" || exit 1
source "${SCRIPT_DIR}/shared" || exit 1

install_dev() {
    if ! install_dev_dependencies; then
        return 1
    fi

    if ! install_dev_requirements; then
        return 1
    fi
}

install_dev_dependencies() {
    info "Installing development dependencies ..."

    if [ -z "${PKG_MGR}" ]; then
        if ! identify_system_pkg_mgr; then
            return 1
        fi
    fi

}

install_docker_fedora() {
    sudo dnf remove -y docker \
        docker-client \
        docker-client-latest \
        docker-common \
        docker-latest \
        docker-latest-logrotate \
        docker-logrotate \
        docker-selinux \
        docker-engine-selinux \
        docker-engine || return 1
    sudo dnf -y install dnf-plugins-core || return 1
    sudo dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo || return 1
    install_packages_with_pkg_mgr "${DNF_DEV_DEPS[@]}"

}

install_prod_requirements() {
    if ! install_lua_pkg "${LUA_DEV_REQ[@]}"; then
        error "Can not install lua requirements."
        return 1
    fi
    success "Installed requirements successfully."
    return 0
}
