#!/usr/bin/env bash

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

source "${SCRIPT_DIR}/utils" || exit 1

TMPFILE=""
NERD_FONTS_PID=""

init_nerd_process() {
    local git_dest_dir="${XDG_DATA_HOME:-$HOME/.local/share}/src"
    NERD_FONTS_DIR="${git_dest_dir}/nerd-fonts"

    if [ -d "${NERD_FONTS_DIR}" ] && dir_is_git_repo "${NERD_FONTS_DIR}"; then
        debug "Nerd-fonts git repo exists. Pulling ..."
        pull_git_dir "${NERD_FONTS_DIR}" || return 2
        return 0
    elif [ ! -d "${NERD_FONTS_DIR}" ]; then
        debug "Nerd-fonts git repo not exists. Cloning ..."
        read -r NERD_FONTS_PID TMPFILE < <(clone_repo https://github.com/ryanoasis/nerd-fonts "${NERD_FONTS_DIR}")
        status=$?
        if [ "${status}" -ne 0 ]; then
            debug "Read exited with ${PIPESTATUS[0]} and clone_repo exited with ${PIPESTATUS[1]}."
            warning "Error occured during clone repo."
            return 3
        fi
        printf pid
        return 0
    else
        error "Directory ${NERD_FONTS_DIR} already exists and is no git repo."
        return 4
    fi
}

kill_nerd_fonts_process() {
    if ! kill "${NERD_FONTS_PID}"; then
        warning "Can not kill nerd-fonts process '${NERD_FONTS_PID}'."
        return 2
    fi
    return 0
}

install_nerd_fonts() {
    wait_for_clone_process "${NERD_FONTS_PID}" "${TMPFILE}" || exit 3
    [ -z "${NERD_FONTS_DIR}" ] && warning "Not Nerd-fonts directory defined." && exit 2
    cd "${NERD_FONTS_DIR}" && chmod +x install.sh || return 2

    local output, status
    output="$(./install.sh 2>&1)"
    status=$?
    if [ "${status}" -ne 0 ]; then
        warning "Install nerd-fonts (instal.sh) exited (${status}) with: ${output}."
        return 1
    fi
    success "Installed nerd-fonts."
    return 0
}
