#!/usr/bin/env bash

[ -z "$SCRIPT_DIR" ] && SCRIPT_DIR="$(pwd)/../scripts"

. "${SCRIPT_DIR}/log"

TMPFILE=$(mktemp)
NERD_FONTS_PROCESS=""

clone_repo() {
    debug "Cloning repo to '${NERDPATH}'"
    git clone --progress https://github.com/ryanoasis/nerd-fonts "${NERDPATH}" >"$TMPFILE" 2>&1 &
    info "Cloned repo"
}

pull_repo() {
    if git -C "${NERDPATH}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        debug "${NERDPATH} is a git repo."
        cd "${NERDPATH}" || return 1
        git pull >"$TMPFILE" 2>&1 &
        NERD_FONTS_PROCESS=$!
        info "Pulling repo."
    else
        warning "${NERDPATH} is not a git repo. Can not pull ..."
    fi
}

init_nerd_process() {
    NERDPATH="${XDG_DATA_HOME:-$HOME/.local/share}/src/nerd-fonts"
    if [ -d "${NERDPATH}" ]; then
        pull_repo
    else
        mkdir -p "${NERDPATH}"
        clone_repo
    fi
}

init_clone_process() {
    init
}

wait_for_clone() {
    info "Waiting for clone process to finish"
    tail -f "${TMPFILE}"
    wait "${NERD_FONTS_PROCESS}"
}

kill_nerd_fonts_process() {
    if ! kill "${NERD_FONTS_PROCESS}"; then
        warning "Can not kill nerd-fonts process '${NERD_FONTS_PROCESS}'."
    fi
}

install_nerd_fonts() {
    wait_for_clone

    cd "${NERDPATH}" || return 1
    chmod +x install.sh
    ./install.sh || return 1
    success "Installed nerd-fonts."
    return 0
}
