return {
	shfmt = "shfmt",
	mdformat = "mdformat",
	stylua = "stylua",
	prettier = "prettier",
	black = "black",
	isort = "isort",
	djlint = "djlint",
	docformatter = "docformatter",
	["clang-format"] = "clang-format",
	cmakelang = "cmakelang",
	yamlfmt = "yamlfmt",
	beautysh = "beautysh",
	rustfmt = "rustfmt",
	xmlformatter = "xmlformatter",
	["google-java-format"] = "google-java-format",
	terraform = "terraform",
}
