return {
	shfmt = "shfmt",
	mdformat = "mdformat",
	stylua = "stylua",
	prettier = "prettier",
	black = "black",
	isort = "isort",
	djlint = "djlint",
	docformatter = "docformatter",
	["clang-format"] = "clang-format",
	cmakelang = "cmakelang",
	yamlfmt = "yamlfmt",
	beautysh = "beautysh",
	rust = "rustfmt",
	["sonarlint-language-server"] = "sonarlint-language-server",
	["google-java-format"] = "google-java-format",
}
