# Build image to build everything.
# Copy required dependencies, requirements, etc to final images.
# This image contains everything which will be later on the local or remote image
#
FROM ubuntu:24.04 AS builder

ARG MAJOR_REQ
ARG MINOR_REQ
ARG PATCH_REQ
