#!/bin/sh

. ./scripts/log

TMPFILE=$(mktemp)

clone_repo() {
    debug "Cloning repo to '${NERDPATH}'"
    git clone https://github.com/ryanoasis/nerd-fonts "${NERDPATH}" >"$TMPFILE" 2>&1 &
    CLONE_PID=$!
    info "Cloned repo"
}

init() {
    NERDPATH="${XDG_DATA_HOME:-$HOME/.local/share}/src/nerd-fonts"
    [ -d "${NERDPATH}" ] || mkdir -p "${NERDPATH}"
}

init_clone_process() {

    init

    if ! clone_repo; then
        warning "Can not clone 'https://github.com/ryanoasis/nerd-fonts'."
        error "Cancel nerd-fonts installation."
    fi
}

wait_for_clone() {
    wait "${CLONE_PID}"

    echo
    echo "========== FULL GIT CLONE OUTPUT =========="
    cat "$TMPFILE"
    rm -f "$TMPFILE"
}

install_nerd_fonts() {
    wait_for_clone

    cd "${NERDPATH}" || return 1
    chmod +x install.sh
    ./install.sh || return 1
    success "Installed nerd-fonts."
    return 0
}
