#!/bin/sh

. ./scripts/log

identify_system_pck_mgr() {
    info "Identifing package manger."
    if command -v apt-get >/dev/null 2>&1; then
        PKGS="neovim git curl gcc clang python3 python3-pip golang nodejs openjdk-21-jdk ninja-build libstdc++-dev luarocks maven g++ pkg-config libssl-dev pre-commit liblua5.4-dev"
        MGR="apt-get"
    elif command -v dnf >/dev/null 2>&1; then
        PKGS="neovim git curl gcc clang python python-pip golang nodejs java-latest-openjdk-devel ninja-build libstdc++-static luarocks maven gcc-c++ pkg-config openssl-devel pre-commit lua-devel"
        MGR="dnf"
    else
        warning "No valid package manager found."
        return 1
    fi
    success "Identified '${MGR}' as package manager."
    return 0
}

install_pck() {
    identify_system_pck_mgr
    info "Install $1."
    install_pcks "$1"
    success "Installed $1"
}

install_pcks() {
    info "Installing dependencies."
    debug "Updating repositories."
    sudo "${MGR}" update || return 1

    debug "Installing dependencies."
    sudo "${MGR}" install -y "$1" || reteurn 1

    success "Installed system packages."
    return 0
}

install_system_dependencies() {
    info "Installing system dependencies for neovim configuration."
    if ! identify_system_pck_mgr; then
        error "Can not install system dependencies. Aboart installation."
        return 1
    fi

    if ! install_pcks $PKGS; then
        error "Can not install packages with the identified package manager. Aboarting."
        return 1
    fi
    return 0
}
