#!/bin/sh

. ./log
. ./install-system-dependencies

install_lua() {
    info "Trying to install lua."
    if [ "$MGR" = "" ]; then
        identify_system_pck_mgr || return 1
    fi
    if [ "$MGR" = "apt-get" ]; then
        install_pck "lua5.4"
    elif [ "$MGR" = "dnf" ]; then
        install_pck "lua"
    fi
    info "Installed lua."
    return 0

}

install_lpeglabel() {
    if ! command -v lua >/dev/null 2>&1; then
        warning "Lua not installed"
        install_lua || return 1
    fi
    info "Installing 'lpeglabel"
    luarocks install lpeglabel --local || return 1
    success "Installed 'lpeglabel'"
    return 0
}
