#!/bin/sh

set -e

get_color() {
    case "$LEVEL" in
        DEBUG) COLOR="\033[37m" ;;
        INFO) COLOR="\033[34m" ;;
        SUCCESS) COLOR="\033[32m" ;;
        WARNING) COLOR="\033[33m" ;;
        ERROR) COLOR="\033[31m" ;;
        *) COLOR="" ;;
    esac
}

log() {
    LEVEL="$1"
    shift
    get_color
    printf "%b[%s]%b %-7s| %b%s%b\n" "\033[36m" "$(date +'%H:%M:%S')" "${COLOR}" "${LEVEL}" "\033[37m" "$*" "\033[0m"
}

debug() {
    log "DEBUG" "$*"
}
info() {
    log "INFO" "$*"
}
success() {
    log "SUCCESS" "$*"
}
warning() {
    log "WARNING" "$*"
}
error() {
    log "ERROR" "$*"
}
