#!/usr/bin/env bash

set -e

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
DEPENDENCIES="${DEPENDENCIES:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../dependencies}"

source "${SCRIPT_DIR}/utils" || exit 1
source "${DEPENDENCIES}" || exit 1

install_nvim() {
    info "Installing neovim."
    local git_dest_dir="${XDG_DATA_HOME:-$HOME/.local/share}/src"
    [ -d "${git_dest_dir}" ] || mkdir -p "${git_dest_dir}"

    local nvim_dir=${git_dest_dir}/neovim

    if [ -d "${nvim_dir}" ] && dir_is_git_repo "${nvim_dir}"; then
        debug "Neovim git repo exists. Pulling ..."
        pull_git_dir "${nvim_dir}" || return 2
    elif [ ! -d "${nvim_dir}" ]; then
        debug "Neovim git repo not exists. Cloning ..."
        if ! git clone --depth=1 https://github.com/neovim/neovim "${nvim_dir}" -b stable; then
            error "Can not clone repo."
            return 3
        fi
    else
        error "Directory ${nvim_dir} already exists and is no git repo."
        return 1
    fi
    debug "Change workdir to ${nvim_dir} and install neovim (stable)"
    cd "${nvim_dir}" && git checkout stable || return 4
    make CMAKE_BUILD_TYPE=Release || return 5
    sudo make install || return 6
    success "Installed $(nvim --version 2>/dev/null | head -n1)."
    return 0
}
