#!/usr/bin/env bash

SCRIPT_DIR="${SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

source "${SCRIPT_DIR}/shared" || exit 1

TMPFILE=""
NERD_FONTS_PID=""

init_nerd_process() {
    local git_dest_dir="${XDG_DATA_HOME:-$HOME/.local/share}/src"
    [ -z "${NERD_FONTS_DIR}" ] && NERD_FONTS_DIR="${git_dest_dir}/nerd-fonts"

    if [ -d "${NERD_FONTS_DIR}" ] && is_repo "${NERD_FONTS_DIR}"; then
        debug "Nerd-fonts git repo exists. Pulling ..."
        pull_repo "${NERD_FONTS_DIR}" || return 2
        return 0
    elif [ ! -d "${NERD_FONTS_DIR}" ]; then
        debug "Nerd-fonts git repo not exists. Cloning ..."
        read -r NERD_FONTS_PID TMPFILE < <(clone_repo https://github.com/ryanoasis/nerd-fonts "${NERD_FONTS_DIR}")
        status=$?
        if [ "${status}" -ne 0 ]; then
            debug "Read exited with ${PIPESTATUS[0]} and clone_repo exited with ${PIPESTATUS[1]}."
            warning "Error occured during clone repo."
            return 3
        fi
        printf pid
        return 0
    else
        error "Directory ${NERD_FONTS_DIR} already exists and is no git repo."
        return 1
    fi
}

kill_nerd_fonts_process() {
    kill_clone_process "${NERD_FONTS_PID}"
}

install_nerd_fonts() {
    wait_for_clone_process "${NERD_FONTS_PID}" "${TMPFILE}" || return 2
    [ -z "${NERD_FONTS_DIR}" ] && warning "Not Nerd-fonts directory defined." && return 3
    cd "${NERD_FONTS_DIR}" && chmod +x install.sh || return 4

    local output status
    output="$(./install.sh 2>&1)"
    status=$?
    if [ "${status}" -ne 0 ]; then
        debug "Install nerd-fonts (instal.sh) exited (${status}) with: ${output}."
        error "Can not install nerd-fonts."
        return 1
    fi
    success "Installed nerd-fonts."
    return 0
}
