FROM fedora:42

ENV DISPLAY=:99
ENV TERM=xterm

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Create TestUser
RUN groupadd tester && useradd -m -g tester tester
ENV HOME=/home/tester
ENV NVIM_CONFIG="${HOME}/.config/nvim"

# clone and install nvim from github.
RUN dnf update -y && dnf install -y ninja-build cmake gcc make gettext curl glibc-gconv-extra git && dnf clean all
ENV MAJOR_REQ=0
ENV MINOR_REQ=11
ENV PATCH_REQ=4

RUN mkdir -p "${HOME}/.local/share/src"
ENV NVIM_GIT_DIR="${HOME}/.local/share/src/neovim"

RUN git clone https://github.com/neovim/neovim -b "v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}" "${NVIM_GIT_DIR}" || exit 1
WORKDIR "${NVIM_GIT_DIR}"
RUN make CMAKE_BUILD_TYPE=Release && make install

ENV BATS_CORE_GIT_DIR="${HOME}/.local/share/src/bats_core"
RUN git clone https://github.com/bats-core/bats-core.git "${BATS_CORE_GIT_DIR}" || exit 1
WORKDIR "${BATS_CORE_GIT_DIR}"
RUN ./install.sh /usr/local

WORKDIR "${HOME}"
# Installing dependencies for nvim plugins.
# Install dependencies via packet manager
RUN dnf update -y && dnf install -y \
    clang \
    gcc-c++ \
    golang \
    java-latest-openjdk-devel \
    libstdc++-static \
    lua \
    luarocks \
    maven \
    nodejs \
    openssl-devel \
    pkg-config \
    pre-commit \
    python \
    python-pip \
    && dnf clean all

# Install rust.
ENV CARGO_HOME="${HOME}/.cargo"
ENV RUSTUP="${HOME}/.rustup"
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y || exit 1
ENV PATH="${CARGO_HOME}/bin:${PATH}"

# Install selene & lpeglabel
# 2 luarocks installs, since otherwise it chrashed because of incompatible versions.
RUN cargo install selene && luarocks install lpeglabel && luarocks install luaunit || exit 1

WORKDIR "${NVIM_CONFIG}"

COPY ./init.lua .
COPY ./lua/lsp ./lua/lsp
COPY ./lua/utils ./lua/utils
COPY ./lua/config ./lua/config
COPY ./lua/plugins ./lua/plugins
COPY ./lazy-lock.json ./lazy-lock.json

RUN chown -R tester:tester "${HOME}"
USER tester

RUN nvim --headless "+InitNVIM"

COPY ./lua/core ./lua/core
COPY ./installs .
COPY ./install .
COPY ./tests .
COPY ./Makefile .

COPY ./env/entrypoint ./env/entrypoint

ENTRYPOINT ["./env/entrypoint"]
