#!/usr/bin/bash

BASH_TESTS_DIR="${NVIM_CONFIG}/tests/bash"

BASH_TEST_FILES=()
COUNTER_SUCCESS_TESTS=()
COUNTER_FAILURE_TESTS=()

function get_bash_test_files() {
    local content=""
    local regex=""
    content="$(cd "${BASH_TESTS_DIR}" && ls -l test_*.bats)"
    regex="^.*(test_.*\.bats)$"
    while IFS= read -r line; do
        if [[ ${line} =~ ${regex} ]]; then
            BASH_TEST_FILES+=("${BASH_REMATCH[1]}")
        fi
    done <<<"${content}"
}

function execute_bash_tests() {
    for test in "${BASH_TEST_FILES[@]}"; do
        output=$(bats "${BASH_TESTS_DIR}/${test}")
        status="$?"
        if [ ${status} -ne 0 ]; then
            printf "%s" "${status}"
        fi
    done
}

get_bash_test_files
execute_bash_tests
