name: Create Main from dev.
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/fedora-nvim:unit-test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}
    steps:
      - name: Prepare Release.
        run: |
          git clone https://github.com/mduessler/nvim-config ${NVIM_CONFIG}
          cd ${NVIM_CONFIG}
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Select files from dev.
        run: |
          git checkout dev -- \
            installs \
            lua \
            .gitignore \
            dependencies \
            init.lua \
            install \
            lazy-lock.json \
            LICENSE \
            README.md
      - name: Remove development section from README.md
        run: sed -i '/^## Development/,/^## Notes & Feedback/ {/^## Notes & Feedback/!d}' README.md
      - name: Release to main.
        run: |
          git add \
            installs \
            lua \
            .gitignore \
            dependencies \
            init.lua \
            install \
            lazy-lock.json \
            LICENSE \
            README.md
          git commit -m "Created new main branch from dev."
          git push orgin main
