name: Create Main from dev.
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/fedora-nvim:unit-test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}
