name: Development
on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container:
      image: ghcr.io/mduessler/fedora-nvim:unit-test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}
    env:
      HOME: /home/tester
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Trust the checkout directo
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Run the linting pre-commit
        run: pre-commit run --all-files
  tests:
    needs: lint
    uses: ./.github/workflows/tests.yaml
    secrets: inherit
