name: Development
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.1.0
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
