name: Development
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/nvim:fedora
      options: --pull=always
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Print all environment variables
        run: env
      - name: Tes
        run: ls -la /__w/ && ls -la /__w/nvim-config
      - name: Map repo to NVIM_CONFIG
        run: |
          mkdir -p $HOME/.config
          ln -s $GITHUB_WORKSPACE $HOME/.config/nvim
          ls -l $HOME/.config/nvim
      - name: Run pre-commit
        run: pre-commit run --all-files
