name: Development
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/nvim:fedora
      options: --pull=always
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run pre-commit
        run: |
          ls -la
          pre-commit run --all-files
          cat /github/home/.cache/pre-commit/pre-commit.log
