name: Development
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/nvim:fedora
      options: --pull=always
    env:
      GITHUB_WORKSPACE: /home/tester/.config/nvim
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run pre-commit
        run: pre-commit run --all-files
