name: Macos
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - install
      - dependencies
      - scripts/**
      - env/entrypoint-install
  workflow_dispatch:
jobs:
  install-test:
    name: install-test-macos
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Run the install test on macos
        run: env/entrypoint-install
